name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint code

    strategy:
      fail-fast: true

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true

      - name: Check formatting
        run: bundle exec standardrb --format=progress

  specs:
    name: Run specs

    env:
      RUN_INTEROPERABILITY_TESTS: "yes"

    strategy:
      fail-fast: true
      matrix:
        ruby: ["2.7", "3.0", "3.1", "3.2", "3.3", "3.4"]

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run specs (Ruby ${{ matrix.ruby }})
        run: bundle exec rspec
